ToDoList/Models/ErrorViewModel.cs
using System;

namespace ToDoList.Models
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

ToDoList/Models/ToDo.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;

namespace ToDoList.Models
{
    public class ToDo
    {
        [Key]

        public int Id { get; set; }
        public string Task { get; set; }
        public  string FromTime { get; set; }
        public string ToTime { get; set; }
    }
}

ToDoList/Controllers/HomeController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using ToDoList.Models;

namespace ToDoList.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

ToDoList/Controllers/ToDoController.cs
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using ToDoList.Data;
using ToDoList.Models;

namespace ToDoList.Controllers
{
    public class ToDoController : Controller
    {
        private readonly ToDoDbContext _db;

        public ToDoController(ToDoDbContext db)
        {
            _db = db;
        }
        public IActionResult Index()
        {
            IEnumerable<ToDo> objList = _db.todo;
          
            return View(objList);
        }

        public IActionResult CreateToDo()
        {
            return View();
        }

        [HttpPost]
        public IActionResult Create(ToDo obj)
        {
            _db.todo.Add(obj);
            _db.SaveChanges();

            return RedirectToAction("Index");
        }

        
        public IActionResult Delete(int id)
        {
            var obj = _db.todo.Find(id);
            _db.todo.Remove(obj);
            _db.SaveChanges();

            return RedirectToAction("Index");
        }
        public IActionResult Edit(int id)
        {
            var obj = _db.todo.Find(id);

            return View(obj);
        }

        [HttpPost]
        public IActionResult PostEdit(ToDo obj)
        {
            _db.todo.Update(obj);
            _db.SaveChanges();

            return RedirectToAction("Index");
        }
    }

}

ToDoList/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4 ">To Do List</h1>
    
</div>

ToDoList/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - ToDoList</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body style="background-color:blanchedalmond">
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container" >
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">To Do List</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                    
                     
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="ToDo" asp-action="Index">View Tasks</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="ToDo" asp-action="CreateToDO">Add Task</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3 ">
         
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted justify-content-center">
       
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

ToDoList/Views/ToDo/CreateToDo.cshtml
@model ToDoList.Models.ToDo

<div class="container h-100 border p-5" style="margin-top:100px ">
    <div class="row h-100 justify-content-center align-items-center">
        <div class="col-10 col-md-8 col-lg-6">
            <form method="post" asp-action="Create" class="h-100 align-items-center align-items-center">

                <div class="form-group">
                    <label class="font-weight-bold" asp-for="Task"></label>
                    <input type="text" asp-for="Task" class="form-control" id="task" placeholder="Enter Task">
                </div>
                <div class="form-group">
                    <label class="font-weight-bold">Start Time</label>
                    <input type="text" asp-for="FromTime" class="form-control" id="startTime" placeholder="Enter Start Time">
                </div>
                <div class="form-group">
                    <label class="font-weight-bold">End Time</label>
                    <input type="text" asp-for="ToTime" class="form-control" id="endTime" placeholder="Enter End Time">
                </div>

                <br />
                <button type="submit" class="btn btn-primary col-12">Add Task</button>
            </form>
        </div>
    </div>
</div>

ToDoList/Views/ToDo/Edit.cshtml
@model ToDoList.Models.ToDo

<div class="container h-100 border p-5" style="margin-top:100px">
    <div class="row h-100 justify-content-center align-items-center">
        <div class="col-10 col-md-8 col-lg-6">
            <form method="post" asp-action="PostEdit" class="h-100 align-items-center align-items-center">
                <input asp-for="Id" hidden/>
                <div class="form-group">
                    <label class="font-weight-bold" asp-for="Task"></label>
                    <input type="text" asp-for="Task" class="form-control" id="task" placeholder="Enter Task">
                </div>
                <div class="form-group">
                    <label class="font-weight-bold">Start Time</label>
                    <input type="text" asp-for="FromTime" class="form-control" id="startTime" placeholder="Enter Start Time">
                </div>
                <div class="form-group">
                    <label class="font-weight-bold">End Time</label>
                    <input type="text" asp-for="ToTime" class="form-control" id="endTime"  placeholder="Enter End Time">
                </div>

                <button type="submit" class="btn btn-primary col-12">Edit Task</button>
            </form>
        </div>
    </div>
</div>

ToDoList/Views/ToDo/Index.cshtml
@model IEnumerable<ToDo>

<div class="container" p-3>
    <div class="row pt-4">
    <div class="col pt-6">
        <h2 class="text-primary">Dinethrex ToDo List</h2>
    </div>
    <div class="col pt-6 text-right">
        <a asp-controller="ToDo" asp-action="CreateToDO">  <button class="btn btn-primary">Add New Task</button></a>
    </div>

        </div>

    <br />
    @if (Model.Count() > 0) { 
    <table class="table table-bordered table-dark table-hover" style="width: 100%; " >
        <thead>
            <tr class="text-center">
                <th>
                    ID
                </th>
                <th>
                    Task
                </th>
                <th>
                    Start Time
                </th>
                <th>
                    End Time
                </th>
                <th>
                    Delete/Edit
                </th>
            </tr>
        </thead>

        <tbody>


            @foreach (var item in Model)
            {
            <tr>
                <td>
                    @item.Id
                </td>
                <td>
                    @item.Task
                </td>
                <td>
                    @item.FromTime
                </td>
                <td>
                    @item.ToTime
                </td>
                <td>
                    <div class="w-100 btn-group justify-content-center"role="group">
                  
                            <a asp-controller="ToDo" asp-action="Delete" asp-route-Id="@item.Id">  <button class="btn btn-danger mx-1 ">Delete</button></a>                    
                            <a asp-controller="ToDo" asp-action="Edit" asp-route-Id="@item.Id">  <button class="btn btn-success mx-1 " style="padding-left:25px;padding-right:25px">Edit</button></a>
                      
                    </div>
                </td>
            </tr>
                    }

             
            </tbody>

    </table>
    }
</div>